/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain;


import de.quinscape.exceedapp.domain.tables.Address;
import de.quinscape.exceedapp.domain.tables.AppState;
import de.quinscape.exceedapp.domain.tables.AppTranslation;
import de.quinscape.exceedapp.domain.tables.AppUser;
import de.quinscape.exceedapp.domain.tables.Customer;
import de.quinscape.exceedapp.domain.tables.Order;
import de.quinscape.exceedapp.domain.tables.OrderItem;
import de.quinscape.exceedapp.domain.tables.Product;
import de.quinscape.exceedapp.domain.tables.records.AddressRecord;
import de.quinscape.exceedapp.domain.tables.records.AppStateRecord;
import de.quinscape.exceedapp.domain.tables.records.AppTranslationRecord;
import de.quinscape.exceedapp.domain.tables.records.AppUserRecord;
import de.quinscape.exceedapp.domain.tables.records.CustomerRecord;
import de.quinscape.exceedapp.domain.tables.records.OrderItemRecord;
import de.quinscape.exceedapp.domain.tables.records.OrderRecord;
import de.quinscape.exceedapp.domain.tables.records.ProductRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>shipping</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AddressRecord> PK_ADDRESS = UniqueKeys0.PK_ADDRESS;
	public static final UniqueKey<AppStateRecord> PK_APP_STATE = UniqueKeys0.PK_APP_STATE;
	public static final UniqueKey<AppTranslationRecord> PK_APP_TRANSLATION = UniqueKeys0.PK_APP_TRANSLATION;
	public static final UniqueKey<AppUserRecord> PK_APP_USER = UniqueKeys0.PK_APP_USER;
	public static final UniqueKey<CustomerRecord> PK_CUSTOMER = UniqueKeys0.PK_CUSTOMER;
	public static final UniqueKey<OrderRecord> PK_ORDER = UniqueKeys0.PK_ORDER;
	public static final UniqueKey<OrderItemRecord> PK_ORDER_ITEM = UniqueKeys0.PK_ORDER_ITEM;
	public static final UniqueKey<ProductRecord> PK_PRODUCT = UniqueKeys0.PK_PRODUCT;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__FK_CUSTOMER_BILLING_ADDRESS_ID = ForeignKeys0.CUSTOMER__FK_CUSTOMER_BILLING_ADDRESS_ID;
	public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__FK_CUSTOMER_DELIVERY_ADDRESS_ID = ForeignKeys0.CUSTOMER__FK_CUSTOMER_DELIVERY_ADDRESS_ID;
	public static final ForeignKey<OrderRecord, CustomerRecord> ORDER__FK_ORDER_CUSTOMER_ID = ForeignKeys0.ORDER__FK_ORDER_CUSTOMER_ID;
	public static final ForeignKey<OrderItemRecord, ProductRecord> ORDER_ITEM__FK_ORDER_ITEM_PRODUCT_ID = ForeignKeys0.ORDER_ITEM__FK_ORDER_ITEM_PRODUCT_ID;
	public static final ForeignKey<OrderItemRecord, OrderRecord> ORDER_ITEM__FK_ORDER_ITEM_ORDER_ID = ForeignKeys0.ORDER_ITEM__FK_ORDER_ITEM_ORDER_ID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AddressRecord> PK_ADDRESS = createUniqueKey(Address.ADDRESS, Address.ADDRESS.ID);
		public static final UniqueKey<AppStateRecord> PK_APP_STATE = createUniqueKey(AppState.APP_STATE, AppState.APP_STATE.ID);
		public static final UniqueKey<AppTranslationRecord> PK_APP_TRANSLATION = createUniqueKey(AppTranslation.APP_TRANSLATION, AppTranslation.APP_TRANSLATION.ID);
		public static final UniqueKey<AppUserRecord> PK_APP_USER = createUniqueKey(AppUser.APP_USER, AppUser.APP_USER.ID);
		public static final UniqueKey<CustomerRecord> PK_CUSTOMER = createUniqueKey(Customer.CUSTOMER, Customer.CUSTOMER.ID);
		public static final UniqueKey<OrderRecord> PK_ORDER = createUniqueKey(Order.ORDER, Order.ORDER.ID);
		public static final UniqueKey<OrderItemRecord> PK_ORDER_ITEM = createUniqueKey(OrderItem.ORDER_ITEM, OrderItem.ORDER_ITEM.ID);
		public static final UniqueKey<ProductRecord> PK_PRODUCT = createUniqueKey(Product.PRODUCT, Product.PRODUCT.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__FK_CUSTOMER_BILLING_ADDRESS_ID = createForeignKey(de.quinscape.exceedapp.domain.Keys.PK_ADDRESS, Customer.CUSTOMER, Customer.CUSTOMER.BILLING_ADDRESS_ID);
		public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__FK_CUSTOMER_DELIVERY_ADDRESS_ID = createForeignKey(de.quinscape.exceedapp.domain.Keys.PK_ADDRESS, Customer.CUSTOMER, Customer.CUSTOMER.DELIVERY_ADDRESS_ID);
		public static final ForeignKey<OrderRecord, CustomerRecord> ORDER__FK_ORDER_CUSTOMER_ID = createForeignKey(de.quinscape.exceedapp.domain.Keys.PK_CUSTOMER, Order.ORDER, Order.ORDER.CUSTOMER_ID);
		public static final ForeignKey<OrderItemRecord, ProductRecord> ORDER_ITEM__FK_ORDER_ITEM_PRODUCT_ID = createForeignKey(de.quinscape.exceedapp.domain.Keys.PK_PRODUCT, OrderItem.ORDER_ITEM, OrderItem.ORDER_ITEM.PRODUCT_ID);
		public static final ForeignKey<OrderItemRecord, OrderRecord> ORDER_ITEM__FK_ORDER_ITEM_ORDER_ID = createForeignKey(de.quinscape.exceedapp.domain.Keys.PK_ORDER, OrderItem.ORDER_ITEM, OrderItem.ORDER_ITEM.ORDER_ID);
	}
}
