/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain;


import de.quinscape.exceedapp.domain.tables.Address;
import de.quinscape.exceedapp.domain.tables.AppConfig;
import de.quinscape.exceedapp.domain.tables.AppLogin;
import de.quinscape.exceedapp.domain.tables.AppTranslation;
import de.quinscape.exceedapp.domain.tables.AppUser;
import de.quinscape.exceedapp.domain.tables.AppUserConfig;
import de.quinscape.exceedapp.domain.tables.Customer;
import de.quinscape.exceedapp.domain.tables.Order;
import de.quinscape.exceedapp.domain.tables.OrderItem;
import de.quinscape.exceedapp.domain.tables.Product;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shipping extends SchemaImpl {

	private static final long serialVersionUID = -1830783881;

	/**
	 * The reference instance of <code>shipping</code>
	 */
	public static final Shipping SHIPPING = new Shipping();

	/**
	 * No further instances allowed
	 */
	private Shipping() {
		super("shipping");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Address.ADDRESS,
			AppConfig.APP_CONFIG,
			AppLogin.APP_LOGIN,
			AppTranslation.APP_TRANSLATION,
			AppUser.APP_USER,
			AppUserConfig.APP_USER_CONFIG,
			Customer.CUSTOMER,
			Order.ORDER,
			OrderItem.ORDER_ITEM,
			Product.PRODUCT);
	}
}
