/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = -942255125;

	private String id;
	private String recipient;
	private String addressLine;
	private String addressExtra;
	private String postal;
	private String country;

	public Address() {}

	public Address(Address value) {
		this.id = value.id;
		this.recipient = value.recipient;
		this.addressLine = value.addressLine;
		this.addressExtra = value.addressExtra;
		this.postal = value.postal;
		this.country = value.country;
	}

	public Address(
		String id,
		String recipient,
		String addressLine,
		String addressExtra,
		String postal,
		String country
	) {
		this.id = id;
		this.recipient = recipient;
		this.addressLine = addressLine;
		this.addressExtra = addressExtra;
		this.postal = postal;
		this.country = country;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 120)
	public String getRecipient() {
		return this.recipient;
	}

	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}

	@NotNull
	@Size(max = 120)
	public String getAddressLine() {
		return this.addressLine;
	}

	public void setAddressLine(String addressLine) {
		this.addressLine = addressLine;
	}

	@Size(max = 120)
	public String getAddressExtra() {
		return this.addressExtra;
	}

	public void setAddressExtra(String addressExtra) {
		this.addressExtra = addressExtra;
	}

	@NotNull
	@Size(max = 120)
	public String getPostal() {
		return this.postal;
	}

	public void setPostal(String postal) {
		this.postal = postal;
	}

	@NotNull
	@Size(max = 120)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
}
