/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppConfig extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = -225058582;

	private String id;
	private String appName;

	public AppConfig() {}

	public AppConfig(AppConfig value) {
		this.id = value.id;
		this.appName = value.appName;
	}

	public AppConfig(
		String id,
		String appName
	) {
		this.id = id;
		this.appName = appName;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}
}
