/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItem extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = 1535991174;

	private String  id;
	private Integer quantity;
	private String  productId;
	private String  orderId;

	public OrderItem() {}

	public OrderItem(OrderItem value) {
		this.id = value.id;
		this.quantity = value.quantity;
		this.productId = value.productId;
		this.orderId = value.orderId;
	}

	public OrderItem(
		String  id,
		Integer quantity,
		String  productId,
		String  orderId
	) {
		this.id = id;
		this.quantity = quantity;
		this.productId = productId;
		this.orderId = orderId;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@NotNull
	@Size(max = 36)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@NotNull
	@Size(max = 36)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}
}
