/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = -454280596;

	private String  id;
	private String  name;
	private String  description;
	private Long    price;
	private String  number;
	private Boolean discontinued;

	public Product() {}

	public Product(Product value) {
		this.id = value.id;
		this.name = value.name;
		this.description = value.description;
		this.price = value.price;
		this.number = value.number;
		this.discontinued = value.discontinued;
	}

	public Product(
		String  id,
		String  name,
		String  description,
		Long    price,
		String  number,
		Boolean discontinued
	) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.price = price;
		this.number = number;
		this.discontinued = discontinued;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@NotNull
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@NotNull
	@Size(max = 36)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@NotNull
	public Boolean getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(Boolean discontinued) {
		this.discontinued = discontinued;
	}
}
