/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables;


import de.quinscape.exceedapp.domain.Keys;
import de.quinscape.exceedapp.domain.Shipping;
import de.quinscape.exceedapp.domain.tables.records.AppConfigRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppConfig extends TableImpl<AppConfigRecord> {

	private static final long serialVersionUID = -1352347735;

	/**
	 * The reference instance of <code>shipping.app_config</code>
	 */
	public static final AppConfig APP_CONFIG = new AppConfig();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppConfigRecord> getRecordType() {
		return AppConfigRecord.class;
	}

	/**
	 * The column <code>shipping.app_config.id</code>.
	 */
	public final TableField<AppConfigRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>shipping.app_config.app_name</code>.
	 */
	public final TableField<AppConfigRecord, String> APP_NAME = createField("app_name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * Create a <code>shipping.app_config</code> table reference
	 */
	public AppConfig() {
		this("app_config", null);
	}

	/**
	 * Create an aliased <code>shipping.app_config</code> table reference
	 */
	public AppConfig(String alias) {
		this(alias, APP_CONFIG);
	}

	private AppConfig(String alias, Table<AppConfigRecord> aliased) {
		this(alias, aliased, null);
	}

	private AppConfig(String alias, Table<AppConfigRecord> aliased, Field<?>[] parameters) {
		super(alias, Shipping.SHIPPING, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppConfigRecord> getPrimaryKey() {
		return Keys.PK_APP_CONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppConfigRecord>> getKeys() {
		return Arrays.<UniqueKey<AppConfigRecord>>asList(Keys.PK_APP_CONFIG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppConfig as(String alias) {
		return new AppConfig(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AppConfig rename(String name) {
		return new AppConfig(name, null);
	}
}
