/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables;


import de.quinscape.exceedapp.domain.Keys;
import de.quinscape.exceedapp.domain.Shipping;
import de.quinscape.exceedapp.domain.tables.records.AppUserConfigRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserConfig extends TableImpl<AppUserConfigRecord> {

	private static final long serialVersionUID = -2089493669;

	/**
	 * The reference instance of <code>shipping.app_user_config</code>
	 */
	public static final AppUserConfig APP_USER_CONFIG = new AppUserConfig();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppUserConfigRecord> getRecordType() {
		return AppUserConfigRecord.class;
	}

	/**
	 * The column <code>shipping.app_user_config.id</code>.
	 */
	public final TableField<AppUserConfigRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>shipping.app_user_config.login</code>.
	 */
	public final TableField<AppUserConfigRecord, String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * Create a <code>shipping.app_user_config</code> table reference
	 */
	public AppUserConfig() {
		this("app_user_config", null);
	}

	/**
	 * Create an aliased <code>shipping.app_user_config</code> table reference
	 */
	public AppUserConfig(String alias) {
		this(alias, APP_USER_CONFIG);
	}

	private AppUserConfig(String alias, Table<AppUserConfigRecord> aliased) {
		this(alias, aliased, null);
	}

	private AppUserConfig(String alias, Table<AppUserConfigRecord> aliased, Field<?>[] parameters) {
		super(alias, Shipping.SHIPPING, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppUserConfigRecord> getPrimaryKey() {
		return Keys.PK_APP_USER_CONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppUserConfigRecord>> getKeys() {
		return Arrays.<UniqueKey<AppUserConfigRecord>>asList(Keys.PK_APP_USER_CONFIG, Keys.UC_APP_USER_CONFIG_LOGIN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AppUserConfigRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AppUserConfigRecord, ?>>asList(Keys.APP_USER_CONFIG__FK_APP_USER_CONFIG_LOGIN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserConfig as(String alias) {
		return new AppUserConfig(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AppUserConfig rename(String name) {
		return new AppUserConfig(name, null);
	}
}
