/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.records;


import de.quinscape.exceedapp.domain.tables.AppConfig;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppConfigRecord extends UpdatableRecordImpl<AppConfigRecord> implements Record2<String, String> {

	private static final long serialVersionUID = 2000725065;

	/**
	 * Setter for <code>shipping.app_config.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>shipping.app_config.id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>shipping.app_config.app_name</code>.
	 */
	public void setAppName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>shipping.app_config.app_name</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getAppName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AppConfig.APP_CONFIG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AppConfig.APP_CONFIG.APP_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAppName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppConfigRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppConfigRecord value2(String value) {
		setAppName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppConfigRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppConfigRecord
	 */
	public AppConfigRecord() {
		super(AppConfig.APP_CONFIG);
	}

	/**
	 * Create a detached, initialised AppConfigRecord
	 */
	public AppConfigRecord(String id, String appName) {
		super(AppConfig.APP_CONFIG);

		setValue(0, id);
		setValue(1, appName);
	}
}
