/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.records;


import de.quinscape.exceedapp.domain.tables.AppLogin;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppLoginRecord extends UpdatableRecordImpl<AppLoginRecord> implements Record5<String, String, String, String, Timestamp> {

	private static final long serialVersionUID = 1795510234;

	/**
	 * Setter for <code>shipping.app_login.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>shipping.app_login.id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>shipping.app_login.username</code>.
	 */
	public void setUsername(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>shipping.app_login.username</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getUsername() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>shipping.app_login.series</code>.
	 */
	public void setSeries(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>shipping.app_login.series</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getSeries() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>shipping.app_login.token</code>.
	 */
	public void setToken(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>shipping.app_login.token</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getToken() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>shipping.app_login.last_used</code>.
	 */
	public void setLastUsed(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>shipping.app_login.last_used</code>.
	 */
	@NotNull
	public Timestamp getLastUsed() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AppLogin.APP_LOGIN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AppLogin.APP_LOGIN.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppLogin.APP_LOGIN.SERIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AppLogin.APP_LOGIN.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return AppLogin.APP_LOGIN.LAST_USED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSeries();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getLastUsed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppLoginRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppLoginRecord value2(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppLoginRecord value3(String value) {
		setSeries(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppLoginRecord value4(String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppLoginRecord value5(Timestamp value) {
		setLastUsed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppLoginRecord values(String value1, String value2, String value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppLoginRecord
	 */
	public AppLoginRecord() {
		super(AppLogin.APP_LOGIN);
	}

	/**
	 * Create a detached, initialised AppLoginRecord
	 */
	public AppLoginRecord(String id, String username, String series, String token, Timestamp lastUsed) {
		super(AppLogin.APP_LOGIN);

		setValue(0, id);
		setValue(1, username);
		setValue(2, series);
		setValue(3, token);
		setValue(4, lastUsed);
	}
}
