/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.records;


import de.quinscape.exceedapp.domain.tables.AppUser;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> implements Record7<String, String, String, Timestamp, Timestamp, String, Boolean> {

	private static final long serialVersionUID = -1301649589;

	/**
	 * Setter for <code>shipping.app_user.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>shipping.app_user.id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>shipping.app_user.login</code>.
	 */
	public void setLogin(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>shipping.app_user.login</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getLogin() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>shipping.app_user.password</code>.
	 */
	public void setPassword(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>shipping.app_user.password</code>.
	 */
	@NotNull
	@Size(max = 255)
	public String getPassword() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>shipping.app_user.created</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>shipping.app_user.created</code>.
	 */
	@NotNull
	public Timestamp getCreated() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>shipping.app_user.last_login</code>.
	 */
	public void setLastLogin(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>shipping.app_user.last_login</code>.
	 */
	@NotNull
	public Timestamp getLastLogin() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>shipping.app_user.roles</code>.
	 */
	public void setRoles(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>shipping.app_user.roles</code>.
	 */
	@NotNull
	@Size(max = 255)
	public String getRoles() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>shipping.app_user.disabled</code>.
	 */
	public void setDisabled(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>shipping.app_user.disabled</code>.
	 */
	public Boolean getDisabled() {
		return (Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, Timestamp, Timestamp, String, Boolean> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, Timestamp, Timestamp, String, Boolean> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AppUser.APP_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AppUser.APP_USER.LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppUser.APP_USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return AppUser.APP_USER.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return AppUser.APP_USER.LAST_LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return AppUser.APP_USER.ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return AppUser.APP_USER.DISABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getLastLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getRoles();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getDisabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value2(String value) {
		setLogin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value3(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value4(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value5(Timestamp value) {
		setLastLogin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value6(String value) {
		setRoles(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value7(Boolean value) {
		setDisabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord values(String value1, String value2, String value3, Timestamp value4, Timestamp value5, String value6, Boolean value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppUserRecord
	 */
	public AppUserRecord() {
		super(AppUser.APP_USER);
	}

	/**
	 * Create a detached, initialised AppUserRecord
	 */
	public AppUserRecord(String id, String login, String password, Timestamp created, Timestamp lastLogin, String roles, Boolean disabled) {
		super(AppUser.APP_USER);

		setValue(0, id);
		setValue(1, login);
		setValue(2, password);
		setValue(3, created);
		setValue(4, lastLogin);
		setValue(5, roles);
		setValue(6, disabled);
	}
}
