/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceedapp.domain.tables.records;


import de.quinscape.exceedapp.domain.tables.Customer;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record6<String, String, String, String, String, String> {

	private static final long serialVersionUID = 951782238;

	/**
	 * Setter for <code>shipping.customer.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>shipping.customer.id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>shipping.customer.salutation</code>.
	 */
	public void setSalutation(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>shipping.customer.salutation</code>.
	 */
	@Size(max = 50)
	public String getSalutation() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>shipping.customer.number</code>.
	 */
	public void setNumber(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>shipping.customer.number</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getNumber() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>shipping.customer.name</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>shipping.customer.name</code>.
	 */
	@NotNull
	@Size(max = 120)
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>shipping.customer.billing_address_id</code>.
	 */
	public void setBillingAddressId(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>shipping.customer.billing_address_id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getBillingAddressId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>shipping.customer.delivery_address_id</code>.
	 */
	public void setDeliveryAddressId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>shipping.customer.delivery_address_id</code>.
	 */
	@Size(max = 36)
	public String getDeliveryAddressId() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Customer.CUSTOMER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Customer.CUSTOMER.SALUTATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Customer.CUSTOMER.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Customer.CUSTOMER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Customer.CUSTOMER.BILLING_ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Customer.CUSTOMER.DELIVERY_ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSalutation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getBillingAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getDeliveryAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value2(String value) {
		setSalutation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value3(String value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value5(String value) {
		setBillingAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value6(String value) {
		setDeliveryAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomerRecord
	 */
	public CustomerRecord() {
		super(Customer.CUSTOMER);
	}

	/**
	 * Create a detached, initialised CustomerRecord
	 */
	public CustomerRecord(String id, String salutation, String number, String name, String billingAddressId, String deliveryAddressId) {
		super(Customer.CUSTOMER);

		setValue(0, id);
		setValue(1, salutation);
		setValue(2, number);
		setValue(3, name);
		setValue(4, billingAddressId);
		setValue(5, deliveryAddressId);
	}
}
